// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщения - это наши структуры данных
type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*LocationData        `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *BatchRequest) GetLocations() []*LocationData {
	if x != nil {
		return x.Locations
	}
	return nil
}

type BatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*LifeScoreResponse   `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *BatchResponse) GetScores() []*LifeScoreResponse {
	if x != nil {
		return x.Scores
	}
	return nil
}

type LocationData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocId         int64                  `protobuf:"varint,1,opt,name=loc_id,json=locId,proto3" json:"loc_id,omitempty"`
	Aq            []*AirQualityData      `protobuf:"bytes,2,rep,name=aq,proto3" json:"aq,omitempty"`
	Weather       []*WeatherData         `protobuf:"bytes,3,rep,name=weather,proto3" json:"weather,omitempty"`
	Anomalies     []*AnomalyData         `protobuf:"bytes,4,rep,name=anomalies,proto3" json:"anomalies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationData) Reset() {
	*x = LocationData{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationData) ProtoMessage() {}

func (x *LocationData) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationData.ProtoReflect.Descriptor instead.
func (*LocationData) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *LocationData) GetLocId() int64 {
	if x != nil {
		return x.LocId
	}
	return 0
}

func (x *LocationData) GetAq() []*AirQualityData {
	if x != nil {
		return x.Aq
	}
	return nil
}

func (x *LocationData) GetWeather() []*WeatherData {
	if x != nil {
		return x.Weather
	}
	return nil
}

func (x *LocationData) GetAnomalies() []*AnomalyData {
	if x != nil {
		return x.Anomalies
	}
	return nil
}

type AirQualityData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pm25          *float64               `protobuf:"fixed64,1,opt,name=pm25,proto3,oneof" json:"pm25,omitempty"`
	Pm10          *float64               `protobuf:"fixed64,2,opt,name=pm10,proto3,oneof" json:"pm10,omitempty"`
	No2           *float64               `protobuf:"fixed64,3,opt,name=no2,proto3,oneof" json:"no2,omitempty"`
	O3            *float64               `protobuf:"fixed64,4,opt,name=o3,proto3,oneof" json:"o3,omitempty"`
	So2           *float64               `protobuf:"fixed64,5,opt,name=so2,proto3,oneof" json:"so2,omitempty"`
	Co            *float64               `protobuf:"fixed64,6,opt,name=co,proto3,oneof" json:"co,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AirQualityData) Reset() {
	*x = AirQualityData{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AirQualityData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirQualityData) ProtoMessage() {}

func (x *AirQualityData) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirQualityData.ProtoReflect.Descriptor instead.
func (*AirQualityData) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *AirQualityData) GetPm25() float64 {
	if x != nil && x.Pm25 != nil {
		return *x.Pm25
	}
	return 0
}

func (x *AirQualityData) GetPm10() float64 {
	if x != nil && x.Pm10 != nil {
		return *x.Pm10
	}
	return 0
}

func (x *AirQualityData) GetNo2() float64 {
	if x != nil && x.No2 != nil {
		return *x.No2
	}
	return 0
}

func (x *AirQualityData) GetO3() float64 {
	if x != nil && x.O3 != nil {
		return *x.O3
	}
	return 0
}

func (x *AirQualityData) GetSo2() float64 {
	if x != nil && x.So2 != nil {
		return *x.So2
	}
	return 0
}

func (x *AirQualityData) GetCo() float64 {
	if x != nil && x.Co != nil {
		return *x.Co
	}
	return 0
}

type WeatherData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temp          *float64               `protobuf:"fixed64,1,opt,name=temp,proto3,oneof" json:"temp,omitempty"`
	Pres          *float64               `protobuf:"fixed64,2,opt,name=pres,proto3,oneof" json:"pres,omitempty"`
	Hum           *float64               `protobuf:"fixed64,3,opt,name=hum,proto3,oneof" json:"hum,omitempty"`
	Wind          *float64               `protobuf:"fixed64,4,opt,name=wind,proto3,oneof" json:"wind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherData) Reset() {
	*x = WeatherData{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherData) ProtoMessage() {}

func (x *WeatherData) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherData.ProtoReflect.Descriptor instead.
func (*WeatherData) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *WeatherData) GetTemp() float64 {
	if x != nil && x.Temp != nil {
		return *x.Temp
	}
	return 0
}

func (x *WeatherData) GetPres() float64 {
	if x != nil && x.Pres != nil {
		return *x.Pres
	}
	return 0
}

func (x *WeatherData) GetHum() float64 {
	if x != nil && x.Hum != nil {
		return *x.Hum
	}
	return 0
}

func (x *WeatherData) GetWind() float64 {
	if x != nil && x.Wind != nil {
		return *x.Wind
	}
	return 0
}

type AnomalyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temp          *float64               `protobuf:"fixed64,1,opt,name=temp,proto3,oneof" json:"temp,omitempty"`
	Hum           *float64               `protobuf:"fixed64,2,opt,name=hum,proto3,oneof" json:"hum,omitempty"`
	Pres          *float64               `protobuf:"fixed64,3,opt,name=pres,proto3,oneof" json:"pres,omitempty"`
	Wind          *float64               `protobuf:"fixed64,4,opt,name=wind,proto3,oneof" json:"wind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnomalyData) Reset() {
	*x = AnomalyData{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnomalyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyData) ProtoMessage() {}

func (x *AnomalyData) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyData.ProtoReflect.Descriptor instead.
func (*AnomalyData) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *AnomalyData) GetTemp() float64 {
	if x != nil && x.Temp != nil {
		return *x.Temp
	}
	return 0
}

func (x *AnomalyData) GetHum() float64 {
	if x != nil && x.Hum != nil {
		return *x.Hum
	}
	return 0
}

func (x *AnomalyData) GetPres() float64 {
	if x != nil && x.Pres != nil {
		return *x.Pres
	}
	return 0
}

func (x *AnomalyData) GetWind() float64 {
	if x != nil && x.Wind != nil {
		return *x.Wind
	}
	return 0
}

type LifeScoreResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LocationId      int64                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	GeneralScore    float64                `protobuf:"fixed64,2,opt,name=general_score,json=generalScore,proto3" json:"general_score,omitempty"`
	AirQuality      int32                  `protobuf:"varint,3,opt,name=air_quality,json=airQuality,proto3" json:"air_quality,omitempty"`
	WeatherQuality  int32                  `protobuf:"varint,4,opt,name=weather_quality,json=weatherQuality,proto3" json:"weather_quality,omitempty"`
	AnomaliesDanger int32                  `protobuf:"varint,5,opt,name=anomalies_danger,json=anomaliesDanger,proto3" json:"anomalies_danger,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LifeScoreResponse) Reset() {
	*x = LifeScoreResponse{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifeScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifeScoreResponse) ProtoMessage() {}

func (x *LifeScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifeScoreResponse.ProtoReflect.Descriptor instead.
func (*LifeScoreResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *LifeScoreResponse) GetLocationId() int64 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *LifeScoreResponse) GetGeneralScore() float64 {
	if x != nil {
		return x.GeneralScore
	}
	return 0
}

func (x *LifeScoreResponse) GetAirQuality() int32 {
	if x != nil {
		return x.AirQuality
	}
	return 0
}

func (x *LifeScoreResponse) GetWeatherQuality() int32 {
	if x != nil {
		return x.WeatherQuality
	}
	return 0
}

func (x *LifeScoreResponse) GetAnomaliesDanger() int32 {
	if x != nil {
		return x.AnomaliesDanger
	}
	return 0
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\tlifescore\"E\n" +
	"\fBatchRequest\x125\n" +
	"\tlocations\x18\x01 \x03(\v2\x17.lifescore.LocationDataR\tlocations\"E\n" +
	"\rBatchResponse\x124\n" +
	"\x06scores\x18\x01 \x03(\v2\x1c.lifescore.LifeScoreResponseR\x06scores\"\xb8\x01\n" +
	"\fLocationData\x12\x15\n" +
	"\x06loc_id\x18\x01 \x01(\x03R\x05locId\x12)\n" +
	"\x02aq\x18\x02 \x03(\v2\x19.lifescore.AirQualityDataR\x02aq\x120\n" +
	"\aweather\x18\x03 \x03(\v2\x16.lifescore.WeatherDataR\aweather\x124\n" +
	"\tanomalies\x18\x04 \x03(\v2\x16.lifescore.AnomalyDataR\tanomalies\"\xca\x01\n" +
	"\x0eAirQualityData\x12\x17\n" +
	"\x04pm25\x18\x01 \x01(\x01H\x00R\x04pm25\x88\x01\x01\x12\x17\n" +
	"\x04pm10\x18\x02 \x01(\x01H\x01R\x04pm10\x88\x01\x01\x12\x15\n" +
	"\x03no2\x18\x03 \x01(\x01H\x02R\x03no2\x88\x01\x01\x12\x13\n" +
	"\x02o3\x18\x04 \x01(\x01H\x03R\x02o3\x88\x01\x01\x12\x15\n" +
	"\x03so2\x18\x05 \x01(\x01H\x04R\x03so2\x88\x01\x01\x12\x13\n" +
	"\x02co\x18\x06 \x01(\x01H\x05R\x02co\x88\x01\x01B\a\n" +
	"\x05_pm25B\a\n" +
	"\x05_pm10B\x06\n" +
	"\x04_no2B\x05\n" +
	"\x03_o3B\x06\n" +
	"\x04_so2B\x05\n" +
	"\x03_co\"\x92\x01\n" +
	"\vWeatherData\x12\x17\n" +
	"\x04temp\x18\x01 \x01(\x01H\x00R\x04temp\x88\x01\x01\x12\x17\n" +
	"\x04pres\x18\x02 \x01(\x01H\x01R\x04pres\x88\x01\x01\x12\x15\n" +
	"\x03hum\x18\x03 \x01(\x01H\x02R\x03hum\x88\x01\x01\x12\x17\n" +
	"\x04wind\x18\x04 \x01(\x01H\x03R\x04wind\x88\x01\x01B\a\n" +
	"\x05_tempB\a\n" +
	"\x05_presB\x06\n" +
	"\x04_humB\a\n" +
	"\x05_wind\"\x92\x01\n" +
	"\vAnomalyData\x12\x17\n" +
	"\x04temp\x18\x01 \x01(\x01H\x00R\x04temp\x88\x01\x01\x12\x15\n" +
	"\x03hum\x18\x02 \x01(\x01H\x01R\x03hum\x88\x01\x01\x12\x17\n" +
	"\x04pres\x18\x03 \x01(\x01H\x02R\x04pres\x88\x01\x01\x12\x17\n" +
	"\x04wind\x18\x04 \x01(\x01H\x03R\x04wind\x88\x01\x01B\a\n" +
	"\x05_tempB\x06\n" +
	"\x04_humB\a\n" +
	"\x05_presB\a\n" +
	"\x05_wind\"\xce\x01\n" +
	"\x11LifeScoreResponse\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x03R\n" +
	"locationId\x12#\n" +
	"\rgeneral_score\x18\x02 \x01(\x01R\fgeneralScore\x12\x1f\n" +
	"\vair_quality\x18\x03 \x01(\x05R\n" +
	"airQuality\x12'\n" +
	"\x0fweather_quality\x18\x04 \x01(\x05R\x0eweatherQuality\x12)\n" +
	"\x10anomalies_danger\x18\x05 \x01(\x05R\x0fanomaliesDanger2\xa8\x01\n" +
	"\x10LifeScoreService\x12O\n" +
	"\x12CalculateLifeScore\x12\x17.lifescore.LocationData\x1a\x1c.lifescore.LifeScoreResponse(\x010\x01\x12C\n" +
	"\x0eCalculateBatch\x12\x17.lifescore.BatchRequest\x1a\x18.lifescore.BatchResponseB\rZ\v./lifescoreb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_service_proto_goTypes = []any{
	(*BatchRequest)(nil),      // 0: lifescore.BatchRequest
	(*BatchResponse)(nil),     // 1: lifescore.BatchResponse
	(*LocationData)(nil),      // 2: lifescore.LocationData
	(*AirQualityData)(nil),    // 3: lifescore.AirQualityData
	(*WeatherData)(nil),       // 4: lifescore.WeatherData
	(*AnomalyData)(nil),       // 5: lifescore.AnomalyData
	(*LifeScoreResponse)(nil), // 6: lifescore.LifeScoreResponse
}
var file_service_proto_depIdxs = []int32{
	2, // 0: lifescore.BatchRequest.locations:type_name -> lifescore.LocationData
	6, // 1: lifescore.BatchResponse.scores:type_name -> lifescore.LifeScoreResponse
	3, // 2: lifescore.LocationData.aq:type_name -> lifescore.AirQualityData
	4, // 3: lifescore.LocationData.weather:type_name -> lifescore.WeatherData
	5, // 4: lifescore.LocationData.anomalies:type_name -> lifescore.AnomalyData
	2, // 5: lifescore.LifeScoreService.CalculateLifeScore:input_type -> lifescore.LocationData
	0, // 6: lifescore.LifeScoreService.CalculateBatch:input_type -> lifescore.BatchRequest
	6, // 7: lifescore.LifeScoreService.CalculateLifeScore:output_type -> lifescore.LifeScoreResponse
	1, // 8: lifescore.LifeScoreService.CalculateBatch:output_type -> lifescore.BatchResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_service_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
