// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LifeScoreService_CalculateLifeScore_FullMethodName = "/lifescore.LifeScoreService/CalculateLifeScore"
	LifeScoreService_CalculateBatch_FullMethodName     = "/lifescore.LifeScoreService/CalculateBatch"
)

// LifeScoreServiceClient is the client API for LifeScoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис - это то, что мы можем вызвать удаленно
type LifeScoreServiceClient interface {
	// RPC метод - удаленная процедура
	// Принимает поток LocationData и возвращает поток LifeScore
	CalculateLifeScore(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LocationData, LifeScoreResponse], error)
	// Для совместимости со старым подходом - батчевый метод
	CalculateBatch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error)
}

type lifeScoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLifeScoreServiceClient(cc grpc.ClientConnInterface) LifeScoreServiceClient {
	return &lifeScoreServiceClient{cc}
}

func (c *lifeScoreServiceClient) CalculateLifeScore(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LocationData, LifeScoreResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LifeScoreService_ServiceDesc.Streams[0], LifeScoreService_CalculateLifeScore_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LocationData, LifeScoreResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LifeScoreService_CalculateLifeScoreClient = grpc.BidiStreamingClient[LocationData, LifeScoreResponse]

func (c *lifeScoreServiceClient) CalculateBatch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchResponse)
	err := c.cc.Invoke(ctx, LifeScoreService_CalculateBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LifeScoreServiceServer is the server API for LifeScoreService service.
// All implementations must embed UnimplementedLifeScoreServiceServer
// for forward compatibility.
//
// Сервис - это то, что мы можем вызвать удаленно
type LifeScoreServiceServer interface {
	// RPC метод - удаленная процедура
	// Принимает поток LocationData и возвращает поток LifeScore
	CalculateLifeScore(grpc.BidiStreamingServer[LocationData, LifeScoreResponse]) error
	// Для совместимости со старым подходом - батчевый метод
	CalculateBatch(context.Context, *BatchRequest) (*BatchResponse, error)
	mustEmbedUnimplementedLifeScoreServiceServer()
}

// UnimplementedLifeScoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLifeScoreServiceServer struct{}

func (UnimplementedLifeScoreServiceServer) CalculateLifeScore(grpc.BidiStreamingServer[LocationData, LifeScoreResponse]) error {
	return status.Error(codes.Unimplemented, "method CalculateLifeScore not implemented")
}
func (UnimplementedLifeScoreServiceServer) CalculateBatch(context.Context, *BatchRequest) (*BatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateBatch not implemented")
}
func (UnimplementedLifeScoreServiceServer) mustEmbedUnimplementedLifeScoreServiceServer() {}
func (UnimplementedLifeScoreServiceServer) testEmbeddedByValue()                          {}

// UnsafeLifeScoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LifeScoreServiceServer will
// result in compilation errors.
type UnsafeLifeScoreServiceServer interface {
	mustEmbedUnimplementedLifeScoreServiceServer()
}

func RegisterLifeScoreServiceServer(s grpc.ServiceRegistrar, srv LifeScoreServiceServer) {
	// If the following call panics, it indicates UnimplementedLifeScoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LifeScoreService_ServiceDesc, srv)
}

func _LifeScoreService_CalculateLifeScore_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LifeScoreServiceServer).CalculateLifeScore(&grpc.GenericServerStream[LocationData, LifeScoreResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LifeScoreService_CalculateLifeScoreServer = grpc.BidiStreamingServer[LocationData, LifeScoreResponse]

func _LifeScoreService_CalculateBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LifeScoreServiceServer).CalculateBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LifeScoreService_CalculateBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LifeScoreServiceServer).CalculateBatch(ctx, req.(*BatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LifeScoreService_ServiceDesc is the grpc.ServiceDesc for LifeScoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LifeScoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lifescore.LifeScoreService",
	HandlerType: (*LifeScoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateBatch",
			Handler:    _LifeScoreService_CalculateBatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CalculateLifeScore",
			Handler:       _LifeScoreService_CalculateLifeScore_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
